# Generated by Django 4.0.5 on 2022-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
    ]
