# Generated by Django 3.2.5 on 2022-06-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='contrasena',
            field=models.CharField(max_length=100),
        ),
    ]
